package policy

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const (
	ExportGroupAll      = "all"
	ExportGroupInbound  = "inbound"
	ExportGroupOutbound = "outbound"
)

// ResolveExportGroup normalizes and validates an export group selector.
func ResolveExportGroup(group string) (string, error) {
	g := strings.TrimSpace(strings.ToLower(group))
	if g == "" {
		g = ExportGroupAll
	}
	switch g {
	case ExportGroupAll, ExportGroupInbound, ExportGroupOutbound:
		return g, nil
	default:
		return "", fmt.Errorf("invalid group %q (must be one of: %s, %s, %s)", group, ExportGroupInbound, ExportGroupOutbound, ExportGroupAll)
	}
}

// FragmentIDsForGroup returns unique package fragment IDs for the requested group.
func FragmentIDsForGroup(pkg *Package, group string) ([]string, error) {
	resolved, err := ResolveExportGroup(group)
	if err != nil {
		return nil, err
	}

	var ids []string
	switch resolved {
	case ExportGroupInbound:
		ids = append(ids, pkg.InboundIDs()...)
	case ExportGroupOutbound:
		ids = append(ids, pkg.OutboundIDs()...)
	default:
		ids = append(ids, pkg.AllFragmentIDs()...)
	}

	seen := make(map[string]bool)
	uniq := make([]string, 0, len(ids))
	for _, id := range ids {
		if !seen[id] {
			seen[id] = true
			uniq = append(uniq, id)
		}
	}
	sort.Strings(uniq)
	return uniq, nil
}

// ExportPackageBicep writes a deployable Bicep bundle for a package.
func ExportPackageBicep(pkg *Package, outDir string, group string) error {
	if pkg == nil {
		return fmt.Errorf("package cannot be nil")
	}
	if strings.TrimSpace(pkg.Manifest.Name) == "" {
		return fmt.Errorf("package manifest is missing required field: name")
	}
	if strings.TrimSpace(pkg.Manifest.Version) == "" {
		return fmt.Errorf("package %q is missing required field: version", pkg.Manifest.Name)
	}

	resolvedGroup, err := ResolveExportGroup(group)
	if err != nil {
		return err
	}
	ids, err := FragmentIDsForGroup(pkg, resolvedGroup)
	if err != nil {
		return err
	}
	if len(ids) == 0 {
		return fmt.Errorf("package %q has no fragments in group %q", pkg.Manifest.Name, resolvedGroup)
	}

	if strings.TrimSpace(outDir) == "" {
		return fmt.Errorf("output directory is required")
	}
	fragmentsDir := filepath.Join(outDir, "fragments")
	if err := os.MkdirAll(fragmentsDir, 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	for _, id := range ids {
		xml, ok := pkg.GetFragmentXML(id)
		if !ok {
			return fmt.Errorf("fragment %q listed in manifest but not found in package files", id)
		}
		target := filepath.Join(fragmentsDir, id+".xml")
		if err := os.WriteFile(target, []byte(xml), 0o644); err != nil {
			return fmt.Errorf("writing fragment %q: %w", id, err)
		}
	}

	bicep := renderBicep(pkg.Manifest.Name, pkg.Manifest.Version, resolvedGroup, ids)
	if err := os.WriteFile(filepath.Join(outDir, "main.bicep"), []byte(bicep), 0o644); err != nil {
		return fmt.Errorf("writing main.bicep: %w", err)
	}

	params := renderBicepParams()
	if err := os.WriteFile(filepath.Join(outDir, "main.bicepparam"), []byte(params), 0o644); err != nil {
		return fmt.Errorf("writing main.bicepparam: %w", err)
	}

	return nil
}

func renderBicep(packageName string, version string, group string, fragmentIDs []string) string {
	var b strings.Builder
	b.WriteString("// Generated by hiddenlayer-apim export bicep\n")
	b.WriteString(fmt.Sprintf("// Package: %s@%s (group: %s)\n\n", packageName, version, group))
	b.WriteString("@description('Name of the Azure API Management service instance')\n")
	b.WriteString("param apimServiceName string\n\n")
	b.WriteString("resource apim 'Microsoft.ApiManagement/service@2023-05-01-preview' existing = {\n")
	b.WriteString("  name: apimServiceName\n")
	b.WriteString("}\n\n")

	for _, id := range fragmentIDs {
		symbol := toBicepSymbol("fragment_" + id)
		b.WriteString(fmt.Sprintf("resource %s 'Microsoft.ApiManagement/service/policyFragments@2023-05-01-preview' = {\n", symbol))
		b.WriteString(fmt.Sprintf("  name: '${apim.name}/%s'\n", id))
		b.WriteString("  properties: {\n")
		b.WriteString(fmt.Sprintf("    description: '%s'\n", fragmentDescription(packageName, version, id)))
		b.WriteString("    format: 'xml'\n")
		b.WriteString(fmt.Sprintf("    value: loadTextContent('fragments/%s.xml')\n", id))
		b.WriteString("  }\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

func renderBicepParams() string {
	return strings.Join([]string{
		"using './main.bicep'",
		"",
		"// Update this file before deployment.",
		"// apimServiceName must match the existing Azure API Management service name.",
		"// Example: 'my-apim-prod'",
		"param apimServiceName = 'your-apim-name'",
		"",
	}, "\n")
}

func toBicepSymbol(name string) string {
	var b strings.Builder
	for i, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			if i == 0 && unicode.IsDigit(r) {
				b.WriteRune('_')
			}
			b.WriteRune(r)
			continue
		}
		b.WriteRune('_')
	}
	s := b.String()
	if s == "" {
		return "fragment_resource"
	}
	return s
}

func fragmentDescription(packageName string, version string, id string) string {
	if strings.TrimSpace(version) != "" {
		return fmt.Sprintf("HiddenLayer %s@%s fragment %s", packageName, version, id)
	}
	return fmt.Sprintf("HiddenLayer %s fragment %s", packageName, id)
}
